Add forked cloud-provider-aws chart
Mirantis/helm-charts pull request #2
Opened 2024-12-18 17:03 UTC by kylewuolle

This adds the ability to set the KubernetesClusterID variable which is needed to ensure hosted AWS templates networking works correctly.

2024-12-18 17:50 UTC, a13x5 requested changes
Several points:
1. The `cloudconfig` subsection should be added to values
2. All conditions should be done with conventional style like `.Values.cloudconfig.enabled`
3. It should be possible to generate the whole cluster config from the values passed, otherwise we doomed to change the chart if we'll want to add another option.
For example the current config should be generated from:
```yaml
cloudconfig:
  enabled: true
  global:
    KubernetesClusterID: "my-cluster"
```

NIT: No CR on the end of most files

2024-12-18 17:50 UTC, a13x5 commented on mirantis/cloud-provider-aws/Chart.yaml
> +version: 0.0.8
Version should be different

2024-12-18 17:50 UTC, a13x5 commented on mirantis/cloud-provider-aws/templates/cloudconfigmap.yaml
> +  name: aws-cloud-config
Use helpers.tpl to define the name as a variable, since you're using it in ds later.

2024-12-18 17:50 UTC, a13x5 commented on mirantis/cloud-provider-aws/templates/cloudconfigmap.yaml
> +apiVersion: v1
Add document separator (`---`) please

2024-12-18 17:50 UTC, a13x5 commented on mirantis/cloud-provider-aws/templates/cloudconfigmap.yaml
> +    KubernetesClusterID = {{ .Values.kubernetesClusterID }}
Config should be generated from values. This hardcode isn't great

2024-12-18 21:41 UTC, kylewuolle commented on mirantis/cloud-provider-aws/Chart.yaml
> +version: 0.0.8
Fixed

2024-12-18 21:46 UTC, kylewuolle commented on mirantis/cloud-provider-aws/templates/cloudconfigmap.yaml
> +  name: aws-cloud-config
done

2024-12-26 19:14 UTC, a13x5 requested changes
Issues with `aws-cloud-config.name` variable

2024-12-26 19:14 UTC, a13x5 commented on mirantis/cloud-provider-aws/templates/_helpers.tpl
> +{{- end }}
You defined an empty variable here. It will render as empty string

2024-12-26 19:14 UTC, a13x5 commented on mirantis/cloud-provider-aws/templates/cloudconfigmap.yaml
> +  name: {{ template "aws-cloud-config.name" . }}
In this case you should use `include`, not `template`.
Applicable to all other cases where this variable is used

2024-12-26 19:48 UTC, a13x5 commented
One more thing I forgot to mention: let's rename the directory to `aws-cloud-controller-manager`, so it will be the same name as defined in chart iself and in the upstream. Right now naming is inconsistent

2025-01-02 17:13 UTC, a13x5 requested changes
The `aws-cloud-config.name` variable is used in weird and flaky way (probably to deal with indentation).
Added several suggestion how to simplify this.

2025-01-02 17:13 UTC, a13x5 commented on mirantis/aws-cloud-controller-manager/templates/_helpers.tpl
> +{{- "aws-cloud-config" }}
There is no need to put curly brackets here. It should be just
```
"aws-cloud-config"
```

2025-01-02 17:13 UTC, a13x5 commented on mirantis/aws-cloud-controller-manager/templates/cloudconfigmap.yaml
> +  name: {{- include "aws-cloud-config.name" . | nindent 4 }}
Why add this `nindent` here? This makes no sense. You can just:

```suggestion
  name: {{ include "aws-cloud-config.name" . }}
```

Applicable to all other usages of this variable.

2025-01-02 17:13 UTC, a13x5 commented on mirantis/aws-cloud-controller-manager/templates/_helpers.tpl
> +{{- define "aws-cloud-config.name" }}
Probably you also need to do, to cope with indentation.  
```suggestion
{{- define "aws-cloud-config.name" -}}
```

2025-01-02 21:14 UTC, a13x5 requested changes
Chart rendering incorrect yaml.
Suggestion added

2025-01-02 21:14 UTC, a13x5 commented on mirantis/aws-cloud-controller-manager/templates/cloudconfigmap.yaml
> +  name: {{- include "aws-cloud-config.name" . }}
This is not rendering correctly, you have trimmed extra whitespace, so it will render as
```yaml
name:"aws-cloud-config"
```

Which is incorrect yaml, you should do something like this (as suggested earlier):

```suggestion
  name: {{ include "aws-cloud-config.name" . }}
```

Applicable to other places with the same issue

2025-01-06 21:34 UTC, a13x5 approved these changes
LGTM

2025-01-06 21:35 UTC, merged